### ISSUE TITLE
Add references (DRKS)

### ISSUE THREAD

**Issue by maia-sh** [bgcarlisle/cthist#10]
It would be great to see when references were added on DRKS, the section is "Trial Publications, Results and other Documents". 

While there is some labeling of reference type, it's not fully structured but perhaps a JSON column would do the trick.
https://www.drks.de/drks_web/navigate.do?navigationId=entryfields&messageDE=Beschreibung%20der%20Eingabefelder&messageEN=Description%20of%20entry%20fields

> Trial Publications, Results and other Documents
> Please select type
> - Paper
> - Abstract
> - Results
> - other documents
> - Background literature
>
> Documents can be submitted as
> - [Free text] for bibliographic reference
> - [Upload] and [Free text] for description of document
> - [URL] and [Free text] for description of document

Here's the code from my simpler scraper if it's helpful: https://github.com/maia-sh/intovalue-data/blob/main/scripts/functions/drks-functions.R#L174

**Comment by bgcarlisle** [comment]
I don't suppose you have an example of a DRKS record that has data under that heading that you'd like to scrape?

**Comment by maia-sh** [comment]
Here's an example: https://www.drks.de/drks_web/navigate.do?navigationId=trial.HTML&TRIAL_ID=DRKS00012795
Would be good to have the label, href and text for each!

```
<ul class="publications">
<li class="publication">
<label>Paper:
							</label>&nbsp;
							<a href="http://dx.doi.org/10.5664/jcsm.6978" target="_new">Glos M, Sabil A, Jelavic KS, Schöbel C, Fietze I, Penzel T. Characterization of respiratory events in obstructive sleep apnea using suprasternal pressure monitoring. J Clin Sleep Med. 2018;14(3):359–369.</a>
</li>
</ul>
```

**Comment by bgcarlisle** [comment]
Okay now here's a version that also contains the references downloader for DRKS.de: https://github.com/bgcarlisle/cthist/commit/39d4db12ffd81631dcb671c0cff8fb3e64153907

If you do the following, for example:

```
library(tidyverse)
library(jsonlite)
library(cthist)

drks_de_download("DRKS00012795") %>%
    select(references) %>%
    slice_tail() %>%
    pull() %>%
    fromJSON() %>%
    tibble() %>%
    select(link) %>%
    pull()
```

That should give you:

`[1] "http://dx.doi.org/10.5664/jcsm.6978"`

**Comment by bgcarlisle** [comment]
Until I find a way to redo DRKS, I won't be able to work on this :(
