### ISSUE TITLE
Add secondary ids

### ISSUE THREAD

**Issue by maia-sh** [bgcarlisle/cthist#14]
Feature request for @bgcarlisle 🥳 

It would be super to be able to get secondary ids from cthist!
We've learned that unfortunately the [AACT `id_information` table](https://aact.ctti-clinicaltrials.org/data_dictionary) does not capture all the id info which we need for non-registration ids, namely grant ids.

Here's a demo of what would be good to capture using [NCT01703273](https://classic.clinicaltrials.gov/ct2/show/NCT01703273):

<img width="600" alt="NCT01703273-secondary-ids" src="https://github.com/bgcarlisle/cthist/assets/38968656/1eb66747-e9c6-46b5-911a-2d92b2b3fe57">

Purple is `id_value` in AACT
Pink is `id_type` in AACT
Blue is missing in AACT

**Comment by bgcarlisle** [comment]
This should do what you need!

https://github.com/bgcarlisle/cthist/commit/afb55447a768ea5576e9b5649e1df6c659573e47

Feel free to re-open this issue if it doesn't work as expected
