### ISSUE TITLE
Timeout errors for large requests

### ISSUE THREAD

**Issue by maia-sh** [bgcarlisle/cthist#18]
@sama9767 is getting timeout issues for large requests (originally ~3000 NCT ids and then even reduced to batches of ~500 ids) with `clinicaltrials_gov_download()`. She has run it overnight for 3 nights and it times out after 1-2 hours. It seems to successfully save what was downloaded before the error, and then is faster on the next iteration, as expected per your documentation.
We wanted to flag this in case it's not expected behavior. She can share the reprex if needed but it's curl and timeout errors.
If this is expected behavior, we'll write a wraparound function to make smaller batches.

Another thought (or feature request) is that it would be great to be able to specify "latest version" instead of {versionno} for `clinicaltrials_gov_version("NCT02110043", {versionno})`, since sometimes we don't need historical versions but just the latest would be ok; however, we don't know know the latest versionno for each NCT id.

Thanks @bgcarlisle

**Comment by bgcarlisle** [comment]
Ah yeah you'd have to do something with the `_dates` function to find out how many versions to get the latest one, but I could write that into it, good suggestion

As for timing out, I haven't done extensive testing on large batches yet, but that's coming for me soon

It should recover after it stops, but I'll have a look at that, thanks for bringing this up!

**Comment by maia-sh** [comment]
Yes, great if you can build latest version into version function. Otherwise, good suggestion for a workaround with dates.

Let us know if we can support on the large batch testing! Feel free to use the intovalue sample that we're trying!

**Comment by bgcarlisle** [comment]
This should help with downloading the latest version

https://github.com/bgcarlisle/cthist/commit/2d5d9f188c34bb12f40bc4ccfdde380fff9e5d7d

(To get this version before it hits CRAN, you'll need to install using `install_github()` via the `devtools` package.)

**Comment by bgcarlisle** [comment]
Let me know if the timeout error is still happening after these bug fixes (just re-open this issue)

If it is, I'll get you to send me the list of NCT's and I'll see if there's a pattern as to when it stops
