### ISSUE TITLE
Helper function for json columns

### ISSUE THREAD

**Issue by maia-sh** [bgcarlisle/cthist#19]
I wanted to flag that I've written a helper function to extract data from the various json columns cthist returns.
Right now, this is living in a project repo, but we now need cthist across projects, so I'm going to pop it out into a little helper package...but before doing so, letting you know in case you think it would have a home in cthist. In that case, very happy to make a pr or for you to just take it and adapt. If it doesn't fit with the package, also understand that!

In any case, would be great to add info about datatypes to flag which are returned in a vector vs. json. Perhaps in https://github.com/bgcarlisle/cthist#what-data-is-extracted

Here's the function: https://github.com/quest-bih/tv-ct-transparency/blob/main/R/functions.R
```r
#' Extract contents from json column and keep unique content for either latest or earliest version
#'
#' @param df Dataframe from \code{cthist::clinicaltrials_gov_download()}
#' @param var JSON column in \code{df} to be parsed
#' @param latest Boolean. Whether to keep latest or earliest version. Defaults to `latest = TRUE`.
#' @return dataframe with id, version number, version date, and json (label and contents)

extract_unique_json <- function(df, var, latest = TRUE) {
  df |>
    select(id, version_number, version_date, {{var}}) |>
    arrange(id) |>

    # Drop rows with empty json
    drop_na({{var}}) |>

    # Extract contacts from json
    mutate(json_col = purrr::map({{var}}, ~ jsonlite::fromJSON(.) |> as.data.frame())) |>
    select(-{{var}}) |>
    tidyr::unnest(json_col) |>

    # Remove rows with no content
    mutate(content = na_if(content, "")) |>
    drop_na(content) |>

    # Keep each unique contact, with latest OR earliest version number
    group_by(id) %>%
    {if(latest) arrange(., desc(version_number)) else arrange(., version_number)} |>
    ungroup() |>
    distinct(id, label, content, .keep_all = TRUE) |>

    # Remove trailing semicolon on label
    mutate(label = stringr::str_remove(label, ":$"))

}
```

And in action:
https://github.com/search?q=repo%3Aquest-bih%2Ftv-ct-transparency%20extract_unique_json&type=code

**Comment by bgcarlisle** [comment]
No let's absolutely pull this into mainline `cthist` for the next version

I'll look at what the function is doing early next week (tomorrow is spoken for and this weekend is Pride in Montreal)

**Comment by bgcarlisle** [comment]
Would you like to do a PR so that you're credited for your work? And would you like to be added as a contributor in the DESCRIPTION file?

I think this function would make a great addition

**Comment by maia-sh** [comment]
Just coming back to this and made a fork to integrate the function, but I see you've refactored so that the json columns are more structured, i.e., not just "content," so I'm not sure the function I wrote is useful anymore, at least not as it stands. I also see you made a specific version for publications. Let me know if a PR would still be useful, and I'm happy to do it. Otherwise, feel free to close this issue; I'll keep the function in the project repo, as I'll use your newer code and hence fancier json going forward.

**Comment by bgcarlisle** [comment]
Oh that may have happened when I had to rewrite for the new site

If there's a helper function that you would find helpful, I can write something similar to the publications function, I just didn't want to do it in a way that cuts you out of being credited for it

But if it's no longer helpful, we don't have to!

**Comment by maia-sh** [comment]
Makes sense! The new json is much better too, so thanks :)
I don't think this generic helper is useful anymore, so I'll keep it in the repo with the older cthist scrapes.
When we use the new and improved cthist, I'll probably get back to you, perhaps with a request or a PR for a helper function.
Thanks again for being awesomely considerate and generous about credit :)
I think this issue can be closed.
