### ISSUE TITLE
Add locations in clinicaltrials_gov_version() 

### ISSUE THREAD

**Issue by YunChiLo** [bgcarlisle/cthist#20]
Hi Benjamin,

This is Vicky Yun-Chi Lo from the University of Adelaide. Thank you so much for developing this useful package. I need this package to download some historical trial data that it currently does not capture. Could you update the function of clinicaltrials_gov_version() to include the "Locations", in addition to the current 16 data points? Many thanks for considering my request.

Cheers,

Vicky

**Comment by bgcarlisle** [comment]
Hi Vicky,

Thanks for reaching out, and I'm glad you find the package useful!

I just want to make sure that I know what data you're after specifically before I start working on this

Can you point me at a specific NCT number for a trial that has the data points you're interested in, and what the values for those are, so I can be sure we both understand the same thing when you're asking for locations?

Thanks!

**Comment by YunChiLo** [comment]
Hi Benjamin,

Thanks for your reply. My study aim is to analyse the distribution of clinical trials by region with different timepoints. Yes, taking a specific clinical trial as an example would be a good idea to clarify the requirement. 

When I conducted a search on the ClinicalTrials.gov website using "NCT05827978", there are 9 versions of this study. Changes of locations occurred in versions 2, 6, 7, 8 and 9, which means some clinical trial sites were added or removed at different timepoints. 

Could you update the function to include the "Locations" shown in the individual version of history of change? Let me know if you need more information. Appreciate your help.

Cheers,

Vicky

**Comment by bgcarlisle** [comment]
Hi Vicky,

Have a look at this:

https://github.com/bgcarlisle/cthist/commit/04551203e0b5b2ef34b55330aebe8615d5d14f2a

If this meets with your approval, you can remove your previous installation of `cthist`:

```
> remove.packages("cthist")
```

Then you can install the development version of `cthist` right now (or you can wait for it to be updated on CRAN, but who knows how long that will take)

To install the development version:

```
> install.packages("devtools")
> devtools::install_github("bgcarlisle/cthist")
```

If you check the version of `cthist` and it's 2.1.9, then you should be able to download the new `locations` column

**Comment by YunChiLo** [comment]
Hi Benjamin,

This is exactly what I need. Thank you so much for the efficient work during the weekend. 

Cheers,

Vicky

**Comment by bgcarlisle** [comment]
Great!

There's some example code in case study 2 of the PLOS One paper that documented version 1.0.0 of this package on how to identify "run lengths" for outcomes that could easily be repurposed for "run lengths" of locations:

https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0270909

And of course, if you find the package useful in your research, I would take it as a kindness if you cited it :)

**Comment by YunChiLo** [comment]
Hi Benjamin,

Sure, I'll cite your package in my research. Thanks for sharing the useful information.

Bets regards,

Vicky
